///////////////////////////////////////////////////////////
//  BehaviorExcutePattern.cs
//  Implementation of the Class BehaviorExcutePattern
//  Generated by Enterprise Architect
//  Created on:      20-十二月-2011 10:13:32
//  Original author: zhanghao
///////////////////////////////////////////////////////////




namespace ZteApp.ProductService.Core {
	public enum BehaviorExecutePattern : int {

		Asynchronization,
		Synchronization

	}//end BehaviorExcutePattern

}//end namespace Core