///////////////////////////////////////////////////////////
//  BehaviorEntityType.cs
//  Implementation of the Class BehaviorEntityType
//  Generated by Enterprise Architect
//  Created on:      26-十二月-2011 10:10:25
//  Original author: zhanghao
///////////////////////////////////////////////////////////




namespace ZteApp.ProductService.Core {
	public enum BehaviorEntityType : int {

		Subject,
		Object,
		Enviroment

	}//end BehaviorEntityType

}//end namespace Core