///////////////////////////////////////////////////////////
//  Priority.cs
//  Implementation of the Class Priority
//  Generated by Enterprise Architect
//  Created on:      31-五月-2012 16:42:05
//  Original author: zhanghao
///////////////////////////////////////////////////////////




namespace ZteApp.ProductService.Core {
	public enum Priority : int {

		High,
		Normal,
		Low

	}//end Priority

}//end namespace Core