///////////////////////////////////////////////////////////
//  WorkStatus.cs
//  Implementation of the Class WorkStatus
//  Generated by Enterprise Architect
//  Created on:      11-六月-2012 8:45:32
//  Original author: zhanghao
///////////////////////////////////////////////////////////




namespace ZteApp.ProductService.Core {
	public enum WorkStatus : int {


		Inactive,
		Working,
		Pause,
		Done,
		Closed


	}//end WorkStatus

}//end namespace Core